version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: "${CONTAINER_PREFIX}_nginx"
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT}:8000"
        volumes: 
            - ./rest-backend:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_docker:latest
        container_name: "${CONTAINER_PREFIX}_php"
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./rest-backend:/var/www/app
        ports: 
            - "${PHP_PORT}:9000"
        networks: 
            - laravel
    
    frontend:
        # build:
        #     context: .
        #     dockerfile: Dockerfile.fe
        image: nginx:alpine
        container_name: "${CONTAINER_PREFIX}_fe"
        restart: unless-stopped
        tty: true
        working_dir: /usr/share/nginx/html
        volumes: 
            - ./frontend:/usr/share/nginx/html
        ports: 
            - "${FE_PORT}:80"
        depends_on: 
            - nginx
        networks: 
            - laravel
